// components/objective/ObjectiveEdit.style.tsx

import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#ffffff" },
  centeredMessageContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  customHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    height: 44,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  headerButton: { padding: 6 },
  headerTitle: { fontSize: 17, fontWeight: "600", color: "#212529" },
  headerSaveButton: { fontSize: 17, fontWeight: "bold", color: "#2b8a3e" },
  coverContainer: {},
  coverImage: {
    height: 200,
    backgroundColor: "#e9ecef",
    justifyContent: "center",
    alignItems: "center",
  },
  editCoverButton: {
    position: "absolute",
    right: 8,
    bottom: 8, // 아바타와 겹치지 않도록 조정
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    padding: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e9ecef",
    opacity: 0.7
  },
  profileSection: {
    paddingHorizontal: 16,
    marginTop: -60,
    alignItems: "center",
  },
  avatarContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#40c057",
    backgroundColor: "#e9ecef",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarImage: { width: "100%", height: "100%", borderRadius: 60 },
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    borderRadius: 60,
    backgroundColor: "#e9ecef",
    justifyContent: "center",
    alignItems: "center",
  },
  typeSelectorContainer: {
    flexDirection: "row",
    justifyContent: "center",
    paddingTop: 24,
    paddingVertical: 16,
  },
  typeButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "#e9ecef",
    marginHorizontal: 8,
  },
  typeButtonSelected: { backgroundColor: "#2b8a3e" },
  typeButtonText: { fontSize: 14, fontWeight: "600", color: "#495057" },
  typeButtonTextSelected: { color: "#ffffff" },
  formWrapper: { paddingBottom: 16 },
  formContainer: { width: "100%", alignItems: "center" },
  titleInput: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#212529",
    textAlign: "center",
    paddingHorizontal: 24,
    marginBottom: 8,
  },
  descriptionInput: {
    fontSize: 16,
    color: "#495057",
    textAlign: "center",
    paddingHorizontal: 24,
    lineHeight: 24,
  },
  gapSection: { paddingTop: 24, borderTopWidth: 8, borderTopColor: "#f1f3f5" },
  sectionDescription: {
    fontSize: 14,
    color: "#868e96",
    paddingHorizontal: 16,
    marginBottom: 16,
    lineHeight: 20,
  },
  viewerContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  viewerImage: { width: "100%", height: "100%" },
  viewerCloseButton: {
    position: "absolute",
    top: Platform.OS === "ios" ? 60 : 20,
    right: 20,
    zIndex: 1,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 16,
    marginTop: 8,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#d8f5a2",
    backgroundColor: "#f4fce3",
    borderRadius: 8,
  },
  addButtonText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: "600",
    color: "#2b8a3e",
  },
  modal: { justifyContent: "flex-end", margin: 0 },
  modalContent: {
    backgroundColor: "white",
    padding: 22,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 40,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 20 },
  modalInput: {
    borderWidth: 1,
    borderColor: "#dee2e6",
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 14,
    fontSize: 16,
    marginBottom: 12,
  },
  saveButton: {
    backgroundColor: "#2b8a3e",
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
    marginTop: 8,
  },
  saveButtonText: { color: "white", fontSize: 16, fontWeight: "bold" },
});

export default styles;
